schema_id: hifi-agent-sample
runtime_config: ../runtime.yaml
sample_id: Candida_albicans
read_technology: pacbio_hifi
hifi_reads:
  - Candida_albicans/Candida_albicans_HiFi.fastq
species_name: Candida albicans
expected_genome_size: 14500000
ploidy: 2
inbred: null
busco_lineage: saccharomycetes_odb12
kmer_reads: null
reference_genome: Candida_albicans/Candida_albicans_gnome.fasta
