sample_id: Candida_albicans
hifi_reads:
  - ../Candida_albicans/Candida_albicans_HIFI.fastq
outdir: ../results/Candida_albicans_phase2
species_name: Candida albicans
expected_genome_size: 14500000
ploidy: 2
inbred: null
busco_lineage: saccharomycetes_odb12
kmer_reads: null
reference_genome: ../Candida_albicans/Candida_albicans_gnome.fasta
resources:
  max_threads: 480
  max_memory_gb: 960
agent:
  max_retry_rounds: 1
  max_candidates_per_round: 2
  objective: balanced
kmer:
  k: 21
